// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // URL used by the Prisma CLI (migrate/db push). The runtime PrismaClient
  // connects via the pg driver adapter (see src/lib/db/prisma.ts).
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
